
services:
  # Serviço do Banco de Dados MySQL
  banco:
    image: mysql:8.0
    container_name: crud_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha_admin_root
      MYSQL_DATABASE: project_pw3crud   # <- Mude para o nome que seu PHP espera
    ports:
      - "3306:3306" # Permite que você acesse o banco pelo DBeaver, MySQL Workbench, etc.
    volumes:
      - dados_mysql:/var/lib/mysql

  # Serviço da sua Aplicação PHP
  web:
    build: .
    container_name: crud_php_app
    restart: always
    ports:
      - "8080:80" # Você vai acessar seu CRUD no navegador via http://localhost:8080
    environment:
      - DB_HOST=banco
      - DB_NAME=project_pw3crud
      - DB_USER=root
      - DB_PASS=senha_admin_root     # <- Passe a senha do root que você definiu acima
    depends_on:
      - banco

volumes:
  dados_mysql: # Garante que os dados do banco não sumam quando os containers pararem