
services:
  
  banco:
    image: mysql:8.0
    container_name: crud_mysql_pw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: project_pw3crud   
    ports:
      - "3307:3306" 
    volumes:
      - dados_mysql:/var/lib/mysql
    
 
  web:
    build: .
    container_name: crud_php_pw
    restart: always
    ports:
      - "8080:80" 
    environment:
      - DB_HOST=banco
      - DB_NAME=project_pw3crud
      - DB_USER=root
      - DB_PASS=root     
    volumes:
      - .:/var/www/html
    depends_on:
      - banco

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: crud_phpmyadmin_pw
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=banco
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - banco

volumes:
  dados_mysql: 